"""Static models of Kodi's include resolution, for structural tests. Conditions, $VAR, $EXP and $INFO are not evaluated.

Two entry points:

- ``resolve_window(filename)`` expands every named include in one window from the definitions in all include files
  (``include_definitions``): <param> defaults and overrides, $PARAM[...] in text and attributes, and the caller's
  other children placed at <nested />. Used by the settings window tests.
- ``Skin`` loads Includes.xml and the files it names in order, keeping the first definition of each include, variable
  and expression name as CGUIIncludes does. The per-install Skin Variables output is skipped unless given, as on a
  fresh install. Used by the Home tests.

``expand_call(name, params)`` expands one include call, for checking what an include produces rather than its
$PARAM plumbing. Conditions are compared by meaning with tests/conditions.py.
"""

import copy
import re
import xml.etree.ElementTree as ET
from pathlib import Path


SKIN = Path(__file__).resolve().parents[1] / "1080i"
XML = SKIN
GENERATED = "script-skinvariables-generator-includes.xml"
PARAM = re.compile(r"\$PARAM\[([^\]]+)\]")

# Bald-native files (CLAUDE.md); the rest of 1080i is Estuary and keeps Estuary's style.
NATIVE = sorted(
    {path for pattern in ("Home.xml", "Includes_Bald_*.xml", "View_51?_*.xml", "View_52?_*.xml", "MyVideoNav.xml",
                          "DialogVideoInfo.xml", "Custom_111[5-8]_*.xml", "SkinSettings.xml", "script-globalsearch.xml",
                          "MyPVRGuide.xml", "DialogContextMenu.xml",
                          "Settings.xml", "SettingsCategory.xml", "SettingsProfile.xml")
     for path in SKIN.glob(pattern)}
    - {SKIN / "Includes_Bald_HomeDefaults.xml"}  # Generated by tools/build_home_defaults.py.
)


def include_definitions(folder=SKIN):
    """Every named <include> in the include files; the per-install Skin Variables output is skipped, as on a fresh
    install, so results do not depend on the local build."""
    definitions = {}
    for path in sorted(folder.glob("*.xml")):
        if path.name == GENERATED:
            continue
        root = ET.parse(path).getroot()
        if root.tag != "includes":
            continue
        for node in root.findall("include"):
            if node.get("name"):
                definitions[node.get("name")] = node
    return definitions


def _params(node):
    return {param.get("name"): param.get("value", param.text or "") for param in node.findall("param")}


def _substitute(element, params):
    def replace(text):
        return PARAM.sub(lambda match: params.get(match.group(1), ""), text) if text else text

    for node in element.iter():
        node.text = replace(node.text)
        node.tail = replace(node.tail)
        for key, value in node.attrib.items():
            node.attrib[key] = replace(value)


# Tags whose whole text Kodi replaces with a <constant>'s value (CGUIIncludes::m_constantNodes, positions and sizes).
CONSTANT_TAGS = {"left", "top", "right", "bottom", "width", "height", "posx", "posy", "centerleft", "centerright",
                 "centertop", "centerbottom", "textoffsetx", "textoffsety", "textwidth", "itemgap"}


def constants(folder=SKIN):
    """Every <constant> in the include files by name, first definition kept, at 1080 (Constants_720.xml skipped)."""
    values = {}
    for path in sorted(folder.glob("*.xml")):
        if path.name in (GENERATED, "Constants_720.xml"):
            continue
        root = ET.parse(path).getroot()
        if root.tag == "includes":
            for node in root.findall("constant"):
                values.setdefault(node.get("name"), node.text or "")
    return values


def resolve_constants(root, values=None):
    """Replace constant names in position and size tags with their values, in place, as Kodi does on load."""
    values = values if values is not None else constants()
    for node in root.iter():
        if node.tag in CONSTANT_TAGS and node.text and node.text.strip() in values:
            node.text = values[node.text.strip()]
    return root


def parse(path):
    """A skin file's root with constants resolved."""
    return resolve_constants(ET.parse(path).getroot())


EXP = re.compile(r"\$EXP\[([^\]]+)\]")


def expressions(folder=SKIN):
    """Every <expression> body in the include files by name, first definition kept; the per-install Skin Variables
    output is skipped as on a fresh install."""
    bodies = {}
    for path in sorted(folder.glob("*.xml")):
        if path.name == GENERATED:
            continue
        root = ET.parse(path).getroot()
        if root.tag == "includes":
            for node in root.findall("expression"):
                bodies.setdefault(node.get("name"), node.text or "")
    return bodies


def expand(text, bodies=None):
    """Replace each $EXP[name] with its body until none is left, as Kodi flattens expressions. Unknown names stay."""
    bodies = bodies if bodies is not None else expressions()
    while True:
        expanded = EXP.sub(lambda match: bodies.get(match.group(1), match.group(0)), text)
        if expanded == text:
            return text
        text = expanded


class UnresolvedInclude(KeyError):
    pass


def _expand_in_place(parent, definitions):
    children = []
    for child in list(parent):
        if child.tag == "include" and not child.get("file"):
            children.extend(_expand_include(child, definitions))
        else:
            _expand_in_place(child, definitions)
            children.append(child)
    for child in list(parent):
        parent.remove(child)
    parent.extend(children)


def _expand_include(call, definitions):
    name = call.get("content") or (call.text or "").strip()
    if name not in definitions:
        raise UnresolvedInclude(name)
    definition = definitions[name]
    params = _params(definition)
    params.update(_params(call))
    body = definition.find("definition")
    source = body if body is not None else definition
    nested = [copy.deepcopy(child) for child in call if child.tag != "param"]

    holder = ET.Element("holder")
    holder.extend(copy.deepcopy(child) for child in source if child.tag != "param")
    _substitute(holder, params)
    for parent in list(holder.iter()):
        for index, child in enumerate(list(parent)):
            if child.tag == "nested":
                parent.remove(child)
                for offset, node in enumerate(nested):
                    parent.insert(index + offset, node)
    _expand_in_place(holder, definitions)
    return list(holder)


def expand_call(name, params=None, definitions=None):
    """What one <include content="name"> call with these params expands to, as a list of elements, nested includes
    and constants resolved. Tests use it to check an include's effective output instead of its $PARAM plumbing."""
    definitions = definitions if definitions is not None else include_definitions()
    call = ET.Element("include", content=name)
    for key, value in (params or {}).items():
        ET.SubElement(call, "param", name=key).text = value
    holder = ET.Element("holder")
    holder.append(call)
    _expand_in_place(holder, definitions)
    return list(resolve_constants(holder))


def resolve_window(filename, definitions=None):
    """Return the window's root element with every static include expanded."""
    definitions = definitions if definitions is not None else include_definitions()
    root = ET.parse(SKIN / filename).getroot()
    _expand_in_place(root, definitions)
    return resolve_constants(root)


class Skin:
    def __init__(self, generated=None):
        self.includes, self.expressions, self.variables = {}, {}, {}
        self.missing = []
        self.generated = generated
        self._load(XML / "Includes.xml")

    def _load(self, path):
        root = ET.parse(path).getroot()
        for node in root.findall("expression"):
            self.expressions.setdefault(node.get("name"), node.text or "")
        for node in root.findall("variable"):
            self.variables.setdefault(node.get("name"), node)
        for node in root.findall("include"):
            if node.get("name") and len(node):
                body = node.find("definition")
                defaults = {param.get("name"): param.get("value", param.text or "") for param in node.findall("param")}
                self.includes.setdefault(node.get("name"), (node if body is None else body, defaults))
            elif node.get("file") == GENERATED:
                if self.generated:
                    self._load(self.generated)
            elif node.get("file") and "IsLessOrEqual(System.ScreenHeight,720)" not in (node.get("condition") or ""):
                self._load(XML / node.get("file"))

    def window(self, name):
        root = ET.parse(XML / name).getroot()
        self._resolve(root)
        return resolve_constants(root)

    def _resolve(self, node):
        while True:
            call = next((child for child in node if child.tag == "include" and not child.get("file")), None)
            if call is None:
                break
            index = list(node).index(call)
            node.remove(call)
            name = call.get("content") or (call.text or "").strip()
            if name not in self.includes:
                self.missing.append(name)
                continue
            body, defaults = self.includes[name]
            params = dict(defaults)
            params.update({param.get("name"): param.get("value", param.text or "") for param in call.findall("param")})
            extra = [child for child in call if child.tag != "param"]
            for child in body:
                if child.tag == "param":
                    continue
                if child.tag == "nested":
                    inserted = [copy.deepcopy(element) for element in extra]
                else:
                    inserted = [copy.deepcopy(child)]
                    marker = inserted[0].find("nested")
                    if marker is not None:
                        at = list(inserted[0]).index(marker)
                        inserted[0].remove(marker)
                        for offset, element in enumerate(extra):
                            inserted[0].insert(at + offset, copy.deepcopy(element))
                    self._params(inserted[0], params)
                for element in inserted:
                    node.insert(index, element)
                    index += 1
        for child in node:
            self._resolve(child)

    @staticmethod
    def _params(node, params):
        def value(match):
            return params.get(match.group(1), "")
        for element in node.iter():
            if element.text:
                element.text = PARAM.sub(value, element.text)
            for key, text in list(element.attrib.items()):
                element.set(key, PARAM.sub(value, text))

    def unknown_references(self, root):
        text = ET.tostring(root, encoding="unicode")
        expressions = set(re.findall(r"\$EXP\[([^\]]+)\]", text)) - set(self.expressions)
        variables = set(re.findall(r"\$VAR\[([^,\]]+)", text))
        for variable in self.variables.values():
            for value in variable.findall("value"):
                variables |= set(re.findall(r"\$VAR\[([^,\]]+)", value.text or ""))
        return sorted(expressions | {f"$VAR[{name}]" for name in variables - set(self.variables)} | set(self.missing))
