"""Repo-wide conventions for the Bald-native XML: named conditions and layout constants."""
import re
import unittest
import xml.etree.ElementTree as ET

from kodi_includes import EXP, SKIN, expressions

# Bald-native files (CLAUDE.md); the rest of 1080i is Estuary and keeps Estuary's style.
NATIVE = sorted(
    {path for pattern in ("Home.xml", "Includes_Bald_*.xml", "View_51?_*.xml", "View_52?_*.xml", "MyVideoNav.xml",
                          "DialogVideoInfo.xml", "Custom_111[5-8]_*.xml", "SkinSettings.xml", "script-globalsearch.xml",
                          "MyPVRGuide.xml", "DialogContextMenu.xml")
     for path in SKIN.glob(pattern)}
    - {SKIN / "Includes_Bald_HomeDefaults.xml"}  # Generated by tools/build_home_defaults.py.
)


def wraps_whole(body):
    """True when the body is one [...] group, ignoring $INFO[...]-style references inside it."""
    body = re.sub(r"\$[A-Z]+\[[^\[\]]*\]", "x", body.strip())
    if not (body.startswith("[") and body.endswith("]")):
        return False
    depth = 0
    for index, char in enumerate(body):
        depth += (char == "[") - (char == "]")
        if depth == 0:
            return index == len(body) - 1
    return False


class ExpressionTests(unittest.TestCase):
    def test_native_expression_bodies_are_bracket_wrapped(self):
        # A wrapped body negates and combines safely wherever $EXP[...] is placed.
        for path in NATIVE:
            root = ET.parse(path).getroot()
            for node in root.iter("expression"):
                with self.subTest(file=path.name, name=node.get("name")):
                    self.assertTrue(wraps_whole(node.text or ""), node.text)

    def test_every_static_expression_reference_resolves(self):
        known = set(expressions())
        for path in NATIVE:
            names = {name for name in EXP.findall(path.read_text()) if "$" not in name}
            with self.subTest(file=path.name):
                self.assertEqual(names - known, set())

    def test_timers_do_not_use_expressions(self):
        # docs/NOTES.md: $EXP in a Timers.xml condition did not trigger in Kodi 22.
        self.assertNotIn("$EXP[", (SKIN / "Timers.xml").read_text())


if __name__ == "__main__":
    unittest.main()
