#!/usr/bin/env python3
"""Build 1080i/Includes_Bald_HomeDefaults.xml, the shipped fallback for the Skin Variables Home rows.

Skin Variables (script.skinvariables, action=buildtemplate) renders shortcuts/skinvariables-generator.json from the
user's row lists into 1080i/script-skinvariables-generator-includes.xml. That file is per-install and not tracked.
Kodi keeps the first definition of an include, variable or expression name, and Includes.xml loads the generated
file before this fallback, so the fallback only fills in until the first build has run (fresh install, or a clone
without a build).

This script renders the same generator config from the shipped row defaults
(shortcuts/skinvariables-shortcut-<menu>.json), following Skin Variables 2.2.4's template rules for the features
Bald's generator files use: datafiles, <lists>, <items menu> loops, <value>, <rules>, <condition> with a==b / a!=b,
$MATH[] (space separated, evaluated left to right) and {name} fields. It also stamps "buildv" in the generator
config with a digest of the generator inputs, so a skin update that changes them makes Skin Variables rebuild
(its build hash covers the config file text, not the files it loads).

  python3 tools/build_home_defaults.py          write both files
  python3 tools/build_home_defaults.py --check  exit 1 if either is out of date
"""

import hashlib
import json
import re
import sys
import xml.etree.ElementTree as ET
from copy import deepcopy
from pathlib import Path
from xml.dom import minidom


ROOT = Path(__file__).resolve().parents[1]
SHORTCUTS = ROOT / "shortcuts"
CONFIG = SHORTCUTS / "skinvariables-generator.json"
OUTPUT = ROOT / "1080i" / "Includes_Bald_HomeDefaults.xml"
NOTE = (
    "<!-- Generated by tools/build_home_defaults.py: what Skin Variables builds from the shipped Home row defaults.\n"
    "     Loaded last from Includes.xml, so the per-install build (script-skinvariables-generator-includes.xml)\n"
    "     wins wherever it exists. Do not edit by hand. -->"
)


class Fields(dict):
    """Unknown {fields} format as empty; {x_escaped} falls back to {x}."""

    def __missing__(self, key):
        if key.endswith("_escaped"):
            return self[key[: -len("_escaped")]]
        return ""


def evaluate_math(text):
    tokens = text.split()
    operators = {"+": lambda a, b: a + b, "-": lambda a, b: a - b, "*": lambda a, b: a * b,
                 "/": lambda a, b: a / b, "**": lambda a, b: a ** b}
    stack, skip = [], False
    for index, token in enumerate(tokens):
        if skip:
            skip = False
            continue
        if token in operators:
            stack.append(float(tokens[index + 1]))
            skip = True
            if len(stack) < 2:
                stack.insert(0, 0.0)
            right = stack.pop()
            left = stack.pop()
            stack.append(operators[token](left, right))
            continue
        stack.append(float(token))
    return stack[-1]


def expand(text, fields):
    text = text.format_map(fields)
    while True:
        match = re.search(r"\$MATH\[(.*?)\]", text)
        if not match:
            return text
        text = text.replace(match.group(0), "{:.0f}".format(evaluate_math(match.group(1))), 1)


def holds(condition):
    if "||" in condition:
        return any(part and holds(part) for part in condition.split("||"))
    if "==" in condition:
        left, right = condition.split("==")
        return left == right
    if "!=" in condition:
        left, right = condition.split("!=")
        return left != right
    if condition.strip().lower() in {"true", ""}:
        return True
    if condition.strip().lower() == "false":
        return False
    raise ValueError(f"condition needs Kodi to evaluate: {condition!r}")


# ---- datafile XML to the generator's dictionary form ----

def read_node(element, meta):
    for tag in ("condition", "datafile"):
        found = [child.text for child in element.findall(tag)]
        if found:
            meta[tag] = found
    template = next((child.text for child in element.findall("template") if child.text), None)
    if template:
        meta["template"] = template
    for child in element:
        if child.tag == "value":
            name = child.get("name", "value")
            if len(child):
                read_node(child, meta.setdefault(name, {}))
            else:
                meta[name] = child.text
        elif child.tag == "rules":
            meta[child.get("name")] = rules = []
            for rule in child.findall("rule"):
                rules.append({})
                read_node(rule, rules[-1])
        elif child.tag == "items":
            meta.update(child.attrib)
            meta["for_each"] = []
            for item in child.findall("item"):
                meta["for_each"].append({})
                read_node(item, meta["for_each"][-1])
        elif child.tag == "lists":
            pairs = []
            for entry in child.findall("list"):
                pairs.append([entry.get("name"), {}])
                read_node(entry, pairs[-1][1])
            if pairs:
                meta["list"] = pairs
    return meta


def load_datafile(name):
    return read_node(ET.fromstring((SHORTCUTS / name).read_text(encoding="utf-8")), {})


def menu_items(menu):
    return json.loads((SHORTCUTS / f"skinvariables-shortcut-{menu}.json").read_text(encoding="utf-8"))


# ---- rendering ----

def render(part, fields):
    part = deepcopy(part)
    fields = Fields(fields)
    if "datafile" in part:
        names = part.pop("datafile")
        merged = {}
        for name in names if isinstance(names, list) else [names]:
            merged.update(load_datafile(name))
        merged.update(part)
        part = merged
    conditions = part.pop("condition", [])
    for condition in conditions if isinstance(conditions, list) else [conditions]:
        if not holds(expand(condition, fields)):
            return []
    if "template" in part:
        return render_template(part, fields)
    if "for_each" in part:
        return render_lists(part, fields) if "list" in part else render_menu(part, fields)
    return []


def render_template(part, fields):
    template = part.pop("template")
    for key, value in part.items():
        if isinstance(value, dict):
            fields[key] = "\n".join(render(value, fields))
        elif isinstance(value, list):
            fields[key] = pick_rule(value, fields)
        else:
            fields[key] = expand(value, fields)
    names = template if isinstance(template, list) else [template]
    texts = []
    for name in names:
        source = (SHORTCUTS / name).read_text(encoding="utf-8") if name.endswith(".xmltemplate") else name
        texts.append(expand(source, fields))
    return ["\n".join(texts)]


def pick_rule(rules, fields):
    for rule in rules:
        conditions = rule.get("condition", ["true"])
        if all(holds(expand(c, fields)) for c in (conditions if isinstance(conditions, list) else [conditions])):
            return expand(rule.get("value") or "", fields)
    return ""


def render_lists(part, fields):
    output = []
    for name, values in part["list"]:
        item_fields = Fields(fields)
        item_fields.update(values)
        item_fields.update({f"parent_{k}": v for k, v in list(item_fields.items())})
        item_fields["item"] = name
        for action in part["for_each"]:
            output += render(action, item_fields)
    return output


def render_menu(part, fields):
    menu = expand(part.get("menu", ""), fields)
    mode = expand(part.get("mode", ""), fields)
    items = menu_items(menu)
    output = []
    for index, entry in enumerate(items):
        for action_index, action in enumerate(part["for_each"]):
            item_fields = Fields(fields)
            item_fields.update({f"parent_{k}": v for k, v in list(item_fields.items())})
            item_fields.update({f"item_{k}": v for k, v in entry.items() if k not in {"submenu", "widgets"}})
            item_fields.update({"item_x": index, "item_action_x": action_index, "item_length_x": len(items),
                                "item_menu": menu, "item_node": "", "item_mode": mode})
            output += render(action, item_fields)
    return output


def build_xml(config):
    content = [config["header"]]
    for part in config["genxml"]:
        content += render(part, config.get("getnfo", {}))
    content.append(config["footer"])
    text = re.sub(r"&(?!amp;|lt;|gt;)", "&amp;", "\n".join(content))
    pretty = minidom.parseString(text).toprettyxml(indent=" " * 4)
    return "\n".join(line for line in pretty.split("\n") if line.strip())


def generator_digest():
    digest = hashlib.sha1()
    inputs = sorted((SHORTCUTS / "generator").iterdir()) + sorted(SHORTCUTS.glob("skinvariables-shortcut-*widgets.json"))
    for path in inputs:
        digest.update(path.relative_to(SHORTCUTS).as_posix().encode())
        digest.update(b"\0")
        digest.update(path.read_bytes())
    return digest.hexdigest()[:12]


def stamped_config_text():
    text = CONFIG.read_text(encoding="utf-8")
    return re.sub(r'"buildv": "[^"]*"', f'"buildv": "{generator_digest()}"', text, count=1)


def fallback_text():
    declaration, body = build_xml(json.loads(CONFIG.read_text(encoding="utf-8"))).split("\n", 1)
    return f"{declaration}\n{NOTE}\n{body}\n"


def main(argv):
    config_text = stamped_config_text()
    fallback = fallback_text()
    if "--check" in argv:
        stale = [path.name for path, text in ((CONFIG, config_text), (OUTPUT, fallback))
                 if path.read_text(encoding="utf-8") != text]
        if stale:
            print("out of date (run tools/build_home_defaults.py): " + ", ".join(stale))
            return 1
        return 0
    CONFIG.write_text(config_text, encoding="utf-8")
    OUTPUT.write_text(fallback, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
