#!/usr/bin/env python3
"""Build the static Home row artwork/caption bindings used by Kodi includes."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "1080i" / "Includes_Bald_HomeRows.xml"
SCREENS = (
    ("home", "Home", 9100),
    ("movies", "Movies", 9200),
    ("tvshows", "TVShows", 9300),
)


def rows():
    for screen, preview, base in SCREENS:
        for index in range(1, 21):
            yield screen, preview, base + index


def preview_condition(screen, preview, row):
    return (
        f"$EXP[Bald_Preview{preview}] + "
        f"String.IsEqual(Window(home).Property(Bald.Row.{screen}),{row})"
    )


def variable_values(art, fallback=None):
    lines = []
    for screen, preview, row in rows():
        condition = preview_condition(screen, preview, row)
        if fallback:
            lines.append(
                f'\t\t<value condition="{condition} + !String.IsEmpty(Container({row}).ListItem.Art({art}))">'
                f'$INFO[Container({row}).ListItem.Art({art})]</value>'
            )
            lines.append(
                f'\t\t<value condition="{condition} + !String.IsEmpty(Container({row}).ListItem.Art({fallback}))">'
                f'$INFO[Container({row}).ListItem.Art({fallback})]</value>'
            )
            lines.append(
                f'\t\t<value condition="{condition}">$INFO[Container({row}).ListItem.Art(thumb)]</value>'
            )
        else:
            lines.append(
                f'\t\t<value condition="{condition} + !String.IsEmpty(Container({row}).ListItem.Art(clearlogo))">'
                f'$INFO[Container({row}).ListItem.Art(clearlogo)]</value>'
            )
            lines.append(
                f'\t\t<value condition="{condition}">$INFO[Container({row}).ListItem.Art(tvshow.clearlogo)]</value>'
            )
    for _, _, row in rows():
        condition = f"String.IsEqual(Window(home).Property(Bald.Row),{row})"
        if fallback:
            lines.append(
                f'\t\t<value condition="{condition} + !String.IsEmpty(Container({row}).ListItem.Art({art}))">'
                f'$INFO[Container({row}).ListItem.Art({art})]</value>'
            )
            lines.append(
                f'\t\t<value condition="{condition} + !String.IsEmpty(Container({row}).ListItem.Art({fallback}))">'
                f'$INFO[Container({row}).ListItem.Art({fallback})]</value>'
            )
            lines.append(
                f'\t\t<value condition="{condition}">$INFO[Container({row}).ListItem.Art(thumb)]</value>'
            )
        else:
            lines.append(
                f'\t\t<value condition="{condition} + !String.IsEmpty(Container({row}).ListItem.Art(clearlogo))">'
                f'$INFO[Container({row}).ListItem.Art(clearlogo)]</value>'
            )
            lines.append(
                f'\t\t<value condition="{condition}">$INFO[Container({row}).ListItem.Art(tvshow.clearlogo)]</value>'
            )
    lines.append("\t\t<value></value>")
    return lines


def logo_condition(row):
    return (
        f"[!String.IsEmpty(Container({row}).ListItem.Art(clearlogo)) | "
        f"!String.IsEmpty(Container({row}).ListItem.Art(tvshow.clearlogo))]"
    )


def expression(name, preview, value):
    parts = []
    for screen, preview_name, row in rows():
        prefix = preview_condition(screen, preview_name, row) if preview else f"String.IsEqual(Window(home).Property(Bald.Row),{row})"
        parts.append(f"[{prefix} + {value(row)}]")
    return f'\t<expression name="{name}">' + " | ".join(parts) + "</expression>"


def configured(name, content):
    lines = [f'\t<include name="{name}">']
    for screen, preview, row in rows():
        condition = preview_condition(screen, preview, row)
        for parity in ("Odd", "Even"):
            lines.append(
                f'\t\t<include content="{content}"><param name="c">{row}</param>'
                f'<param name="p">{parity}</param><param name="preview">{condition}</param></include>'
            )
    lines.append("\t</include>")
    return lines


lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<includes>",
    "\t<!-- Generated by tools/build_home_row_bindings.py. Twenty configurable rows per screen. -->",
    '\t<variable name="Bald_Fanart">',
    *variable_values("fanart", "tvshow.fanart"),
    "\t</variable>",
    '\t<variable name="Bald_Logo">',
    *variable_values("clearlogo"),
    "\t</variable>",
    expression("Bald_HasLogo", False, logo_condition),
    expression("Bald_ItemOdd", False, lambda row: f"Integer.IsOdd(Container({row}).CurrentItem)"),
    expression("Bald_PreviewHasLogo", True, logo_condition),
    expression("Bald_PreviewItemOdd", True, lambda row: f"Integer.IsOdd(Container({row}).CurrentItem)"),
    *configured("Bald_ConfiguredArtLogos", "Bald_ArtLogo"),
    *configured("Bald_ConfiguredCaptions", "Bald_Caption"),
    "</includes>",
    "",
]

OUTPUT.write_text("\n".join(lines), encoding="utf-8")
